#!/usr/bin/env python3

import csv
from lib import *
import os
import re
import sys
import time
import functools

CSV_SEP = '\x1F'
TAG_SEP = '\x1E'
API_KEY = os.environ['LASTFM_API_KEY']

def cleaner(elem):
    elem = re.sub(r'\(.*\)', '', elem)
    return elem.strip()

@functools.lru_cache(maxsize=None)
def get_elems(track, artist):
    time.sleep(1/4) # because lastfm do not want too much

    req = get('http://ws.audioscrobbler.com/2.0/', params={
        'method': 'track.gettoptags',
        'artist': artist,
        'track': track,
        'autocorrect': 1,
        'api_key': API_KEY,
        'format': 'json',
    })

    json = req.json()
    error = json.get('error')
    if error is not None and error == 6:
        return date, track, artist, ''

    json_toptags = req.json()['toptags']

    json_attr = json_toptags['@attr']
    artist = json_attr['artist']
    track = json_attr['track']

    tags = [json_tag['name'] for json_tag in json_toptags['tag'] if json_tag['count'] >= 10]

    return date, track, artist, TAG_SEP.join(tags)

reader = csv.reader(sys.stdin, delimiter=CSV_SEP)
for date, track, artist in reader:
    artist = cleaner(artist)
    track = cleaner(track)

    line = get_elems(track, artist)
    line.insert(0, date)

    if line[-1] == '':
        print(line)
